#!/usr/bin/python3
# -*- coding: utf-8 -*-
 
import cgi
 
html_body = """
&amp;lt;!DOCTYPE html&amp;gt;
&amp;lt;html&amp;gt;
&amp;lt;head&amp;gt;
&amp;lt;title&amp;gt;foo表示&amp;lt;/title&amp;gt;
&amp;lt;/head&amp;gt;
&amp;lt;body&amp;gt;
&amp;lt;B&amp;gt;foo=%s&amp;lt;/B&amp;gt;
&amp;lt;/body&amp;gt;
&amp;lt;/html&amp;gt;
"""
 
form = cgi.FieldStorage()
text = form.getvalue('foo','')
 
print(html_body % (text))